create table if not exists app_user (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password_hash varchar(100) not null,
    display_name varchar(100),
    enabled boolean not null,
    created_at timestamp
);

create table if not exists survey_result (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    concern_area varchar(50) not null,
    survey_name varchar(255),
    survey_key_features varchar(2000),
    response1 integer,
    response2 integer,
    response3 integer,
    response4 integer,
    response5 integer,
    response6 integer,
    response7 integer,
    response8 integer,
    response9 integer,
    total_score integer,
    percentage_score integer,
    severity_label varchar(255),
    recommendation varchar(2000),
    urgent_support_suggested boolean,
    created_at timestamp
);

create table if not exists assessment_result (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    sleep_hours integer,
    age_group varchar(50),
    energy_level varchar(50),
    anxiety_level varchar(50),
    support_level varchar(50),
    recommendation varchar(2000),
    wellness_band varchar(255),
    created_at timestamp
);

create table if not exists journal_entry (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    entry_date date not null,
    mood varchar(50) not null,
    workload_pressure integer not null,
    sleep_difficulty integer not null,
    focus_difficulty integer not null,
    support_difficulty integer not null,
    stress_score integer,
    stress_category varchar(255),
    note varchar(1000) not null,
    created_at timestamp
);
