create table if not exists survey_result (
    id bigint generated by default as identity primary key,
    concern_area varchar(50) not null,
    survey_name varchar(255),
    survey_key_features varchar(2000),
    response1 integer,
    response2 integer,
    response3 integer,
    response4 integer,
    response5 integer,
    response6 integer,
    response7 integer,
    response8 integer,
    response9 integer,
    total_score integer,
    percentage_score integer,
    severity_label varchar(255),
    recommendation varchar(2000),
    urgent_support_suggested boolean,
    created_at timestamp
);

create table if not exists journal_entry (
    id bigint generated by default as identity primary key,
    entry_date date not null,
    mood varchar(50) not null,
    workload_pressure integer not null,
    sleep_difficulty integer not null,
    focus_difficulty integer not null,
    support_difficulty integer not null,
    stress_score integer,
    stress_category varchar(255),
    note varchar(1000) not null,
    created_at timestamp
);
